version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ./frontend.dockerfile
            args:
                VITE_API_URL: http://88.210.9.124:5555
        ports:
            - "5173:5173"
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: ./backend.dockerfile
        ports:
            - "5555:5555"
