version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: build.dockerfile
            target: frontend
        ports:
            - "5555:5173"
        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: build.dockerfile
            target: backend
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
