version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: frontend/frontend.dockerfile
            target: frontend
        ports:
            - "5173:5173"
        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: backend/backend.dockerfile
            target: backend
        ports:
            - "5555:5555"
        environment:
            - NODE_ENV=production
